/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mio_jni_NativeHelper */

#ifndef _Included_com_mio_jni_NativeHelper
#define _Included_com_mio_jni_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mio_jni_NativeHelper
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mio_jni_NativeHelper_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mio_jni_NativeHelper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mio_jni_NativeHelper_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mio_jni_NativeHelper
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mio_jni_NativeHelper_stringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
